using System.Linq;
using System.Text;
using System.Text.Json;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Sharpmine.Gen;

namespace Sharpmine.Domain.Gen;

[Generator]
public class RegistryKeyGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registryContents = context.AdditionalTextsProvider
            .Where(static file => file.Path.Replace('\\', '/').EndsWith("/reports/registries.json"))
            .Select(static (text, ct) => text.GetText(ct)?.ToString())
            .Collect();

        context.RegisterSourceOutput(registryContents, (spc, allContents) =>
        {
            if (allContents.IsDefaultOrEmpty) return;

            string? content = allContents.FirstOrDefault(c => !string.IsNullOrWhiteSpace(c));
            if (string.IsNullOrWhiteSpace(content)) return;

            var sb = new StringBuilder("""
                                       // <auto-generated/>

                                       using Sharpmine.Domain;

                                       namespace Sharpmine.Domain.Registries.Static;

                                       public static class RegistryKeys
                                       {

                                       """);

            try
            {
                var root = JsonElement.Parse(content!);

                foreach (string fullId in root.EnumerateObject().Select(registry => registry.Name))
                {
                    string propertyName = GeneratorUtils.ToPascalCase(fullId.Replace("minecraft:", string.Empty));
                    sb.AppendLine($"    public static readonly Identifier {propertyName} = \"{fullId}\";");
                }
            }
            catch
            {
                sb.AppendLine("    // Error parsing JSON");
            }

            sb.AppendLine("}");
            spc.AddSource("RegistryKeys.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

}
