using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class BlockRegistryGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var blockContents = context.AdditionalTextsProvider
            .Where(static file => file.Path.Replace('\\', '/').EndsWith("/reports/blocks.json", System.StringComparison.OrdinalIgnoreCase))
            .Select(static (text, cancellationToken) => text.GetText(cancellationToken)?.ToString())
            .Collect();

        context.RegisterSourceOutput(blockContents, static (sourceProductionContext, allContents) =>
        {
            if (allContents.IsDefaultOrEmpty) return;

            string? content = allContents.FirstOrDefault(c => !string.IsNullOrWhiteSpace(c));
            if (string.IsNullOrWhiteSpace(content)) return;

            var sb = new StringBuilder("""
                                       // <auto-generated/>

                                       using System.Collections.Frozen;
                                       using System.Collections.Generic;
                                       using System.Collections.Immutable;
                                       using Sharpmine.Domain;
                                       using Sharpmine.Domain.Blocks;

                                       namespace Sharpmine.Domain.Registries.Static;

                                       public static class Blocks
                                       {

                                       """);

            var generatedBlocks = new List<(string PropertyName, string FullId)>();

            try
            {
                using var document = JsonDocument.Parse(content!);
                var root = document.RootElement;

                foreach (var blockProperty in root.EnumerateObject())
                {
                    string possiblePropsArg;

                    if (blockProperty.Value.TryGetProperty("properties", out var possiblePropsNode))
                    {
                        var dictEntries = possiblePropsNode
                            .EnumerateObject()
                            .Select(p =>
                            {
                                var allowedValues = p.Value.EnumerateArray().Select(v => $"\"{v.GetString()}\"");
                                return $"{{ \"{p.Name}\", [{string.Join(", ", allowedValues)}] }}";
                            });

                        possiblePropsArg = $"new() {{ {string.Join(", ", dictEntries)} }}";
                    }
                    else
                    {
                        possiblePropsArg = "[]";
                    }

                    string fullId = blockProperty.Name;
                    string propertyName = GeneratorUtils.ToPascalCase(fullId.Replace("minecraft:", string.Empty));
                    var statesBuilder = new StringBuilder();
                    var statesNode = blockProperty.Value.GetProperty("states");
                    bool firstState = true;

                    foreach (var state in statesNode.EnumerateArray())
                    {
                        if (!firstState) statesBuilder.Append(", ");

                        int id = state.GetProperty("id").GetInt32();
                        bool isDefault = state.TryGetProperty("default", out var def) && def.GetBoolean();
                        string propsArg;

                        if (state.TryGetProperty("properties", out var props))
                        {
                            var dictEntries = props
                                .EnumerateObject()
                                .Select(p => $"{{ \"{p.Name}\", \"{p.Value.GetString()}\" }}");

                            propsArg = $"new() {{ {string.Join(", ", dictEntries)} }}";
                        }
                        else
                        {
                            propsArg = "[]";
                        }

                        statesBuilder.Append($"new BlockState({id}, {(isDefault ? "true" : "false")}, {propsArg})");
                        firstState = false;
                    }

                    sb.AppendLine($"""
                                       public static readonly Block {propertyName} = new Block(
                                           "{fullId}", 
                                           [{statesBuilder}],
                                           {possiblePropsArg});
                                   """);

                    generatedBlocks.Add((propertyName, fullId));
                }

                sb.AppendLine("    public static readonly FrozenDictionary<Identifier, Block> All = new Dictionary<Identifier, Block>");
                sb.AppendLine("    {");

                foreach (var block in generatedBlocks)
                {
                    sb.AppendLine($"        {{ \"{block.FullId}\", {block.PropertyName} }},");
                }

                sb.AppendLine("    }.ToFrozenDictionary();");
            }
            catch
            {
                sb.AppendLine("    // Error parsing JSON");
            }

            sb.AppendLine("}");
            sourceProductionContext.AddSource("Blocks.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

}
