using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class ItemRegistryGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var itemContents = context.AdditionalTextsProvider
            .Where(static file => file.Path.Replace('\\', '/')
                .EndsWith("/reports/items.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, ct) => text.GetText(ct)?.ToString())
            .Collect();

        context.RegisterSourceOutput(itemContents, static (spc, allContents) =>
        {
            if (allContents.IsDefaultOrEmpty) return;

            string? content = allContents.FirstOrDefault(c => !string.IsNullOrWhiteSpace(c));
            if (string.IsNullOrWhiteSpace(content)) return;

            var sb = new StringBuilder("""
                                       // <auto-generated/>

                                       using System.Collections.Frozen;
                                       using System.Collections.Generic;
                                       using Sharpmine.Domain;
                                       using Sharpmine.Domain.Items;

                                       namespace Sharpmine.Domain.Registries.Static;

                                       public static class Items
                                       {

                                       """);

            var generatedItems = new List<(string PropertyName, string FullId)>();

            try
            {
                using var document = JsonDocument.Parse(content!);
                var root = document.RootElement;

                foreach (string fullId in root.EnumerateObject().Select(itemProperty => itemProperty.Name))
                {
                    string propertyName = GeneratorUtils.ToPascalCase(fullId.Replace("minecraft:", string.Empty));
                    sb.AppendLine($"    public static readonly Item {propertyName} = new Item(\"{fullId}\");");
                    generatedItems.Add((propertyName, fullId));
                }

                sb.AppendLine();
                sb.AppendLine("    public static readonly FrozenDictionary<Identifier, Item> All = new Dictionary<Identifier, Item>");
                sb.AppendLine("    {");
                foreach (var item in generatedItems)
                {
                    sb.AppendLine($"        {{ \"{item.FullId}\", {item.PropertyName} }},");
                }

                sb.AppendLine("    }.ToFrozenDictionary();");
            }
            catch
            {
                sb.AppendLine("    // Error parsing JSON");
            }

            sb.AppendLine("}");
            spc.AddSource("Items.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

}
