using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class PacketGenerator : IIncrementalGenerator
{

    private const string BaseNamespace = "Sharpmine.Server.Protocol.Packets";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packetProvider = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("packets.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, cancellationToken) => ParsePackets(text.GetText(cancellationToken)?.ToString()))
            .SelectMany(static (packets, _) => packets)
            .Collect();

        context.RegisterSourceOutput(packetProvider, Execute);
    }

    private static ImmutableArray<PacketModel> ParsePackets(string? jsonContent)
    {
        if (string.IsNullOrWhiteSpace(jsonContent))
        {
            return ImmutableArray<PacketModel>.Empty;
        }

        using var doc = JsonDocument.Parse(jsonContent!);
        var builder = ImmutableArray.CreateBuilder<PacketModel>();

        var orderedStateProperties = doc.RootElement
            .EnumerateObject()
            .OrderBy(static prop => (prop.Value.TryGetProperty("serverbound", out var sb))
                ? sb.GetPropertyCount() 
                : 0);

        foreach (var stateProperty in orderedStateProperties)
        {
            string stateName = ToPascalCase(stateProperty.Name);
            GenerateProtocolDirection(stateProperty, "Serverbound", stateName, builder);
            GenerateProtocolDirection(stateProperty, "Clientbound", stateName, builder);
        }

        return builder.ToImmutable();
    }

    private static void GenerateProtocolDirection(
        JsonProperty stateProperty,
        string directionName,
        string stateName,
        ImmutableArray<PacketModel>.Builder builder)
    {
        if (!stateProperty.Value.TryGetProperty(directionName.ToLower(), out var packetsElement))
        {
            return;
        }

        foreach (var packet in packetsElement.EnumerateObject())
        {
            int id = packet.Value.GetProperty("protocol_id").GetInt32();
            string rawName = packet.Name.StartsWith("minecraft:") ? packet.Name.Substring(10) : packet.Name;
            string className = ToPascalCase(rawName) + "Packet";
            builder.Add(new PacketModel(stateName, directionName, className, id));
        }
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<PacketModel> packets)
    {
        if (packets.IsDefaultOrEmpty) return;

        foreach (var packet in packets)
        {
            GeneratePacketPartial(context, packet);
        }

        GenerateRegistry(context, [.. packets.Where(p => p.Direction == "Serverbound")]);
    }

    private static void GeneratePacketPartial(SourceProductionContext context, PacketModel packet)
    {
        string source = $$"""
                          // <auto-generated />

                          using System;

                          namespace {{BaseNamespace}}.{{packet.StateName}}.{{packet.Direction}};

                          public partial record {{packet.ClassName}} : I{{packet.Direction}}Packet 
                          {
                              public ProtocolState State => ProtocolState.{{packet.StateName}};
                              public int Id => 0x{{packet.Id:X2}};
                          }
                          """;

        context.AddSource($"{typeof(PacketGenerator)}_{packet.StateName}.{packet.Direction}/{packet.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static void GenerateRegistry(SourceProductionContext context, ImmutableArray<PacketModel> serverboundPackets)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
                        // <auto-generated />

                        #nullable enable

                        using System.Diagnostics.CodeAnalysis;

                        namespace {{BaseNamespace}};

                        public static class ServerboundPacketRegistry 
                        {
                            public static bool TryCreatePacket(
                                ProtocolState state,
                                int id,
                                [NotNullWhen(true)] out IServerboundPacket? packet)
                            {
                                packet = (state, id) switch
                                {
                        """);

        foreach (var packet in serverboundPackets)
        {
            sb.AppendLine($"            (ProtocolState.{packet.StateName}, 0x{packet.Id:X2}) => new {packet.StateName}.Serverbound.{packet.ClassName}(),");
        }

        sb.Append("""
                              _ => null
                          };
                      
                          return packet is not null;
                      }
                  }
                  """);

        context.AddSource($"{typeof(PacketGenerator)}_Registry/ServerboundPacketRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string ToPascalCase(string input)
    {
        return string.Join(
            string.Empty,
            input.Split(['_', '/'], StringSplitOptions.RemoveEmptyEntries)
                .Select(static word => char.ToUpper(word[0]) + word.Substring(1)));
    }

    private readonly record struct PacketModel(string StateName, string Direction, string ClassName, int Id);

}
