using System;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class PacketGenerator : IIncrementalGenerator
{

    private const string BaseNamespace = "Sharpmine.Server.Protocol.Packets";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packetProvider = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("packets.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, cancellationToken) => text.GetText(cancellationToken)?.ToString());

        context.RegisterSourceOutput(packetProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, string? jsonContent)
    {
        if (string.IsNullOrWhiteSpace(jsonContent))
        {
            return;
        }

        using var doc = JsonDocument.Parse(jsonContent!);
        var sb = new StringBuilder();
        StartRegistry(sb);

        var orderedStateProperties = doc.RootElement
            .EnumerateObject()
            .OrderBy(static prop => prop.Value
                .GetProperty("serverbound")
                .GetPropertyCount()
            );

        foreach (var stateProperty in orderedStateProperties)
        {
            GenerateProtocolDirection(context, stateProperty, "Serverbound", sb);
            GenerateProtocolDirection(context, stateProperty, "Clientbound", null);
        }

        EndRegistry(sb);
        context.AddSource("Registry/ServerboundPacketRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateProtocolDirection(
        SourceProductionContext context,
        JsonProperty stateProperty,
        string directionName,
        StringBuilder? sb
    )
    {
        if (!stateProperty.Value.TryGetProperty(directionName.ToLower(), out var packetsElement))
        {
            return;
        }

        string stateName = ToPascalCase(stateProperty.Name);
        string interfaceName = $"I{directionName}Packet";

        var orderedPackets = packetsElement.EnumerateObject()
            .Select(static prop => (prop.Name, Id: prop.Value.GetProperty("protocol_id").GetInt32()))
            .OrderBy(static prop => prop.Id);

        foreach (var packet in orderedPackets)
        {
            string packetName = packet.Name.Substring("minecraft:".Length);
            string packetClassName = ToPascalCase(packetName) + "Packet";
            GeneratePacketPartial(context, packetClassName, interfaceName, stateName, directionName, packet.Id);
            sb?.AppendLine($"            (ProtocolState.{stateName}, 0x{packet.Id:X2}) => {stateName}.{directionName}.{packetClassName}.DeserializeAsync(stream, reader, cancellationToken),");
        }
    }

    private static void GeneratePacketPartial(
        SourceProductionContext context,
        string className,
        string interfaceName,
        string stateName,
        string directionName,
        int id
    )
    {
        string source = $$"""
                          // <auto-generated />

                          using System;

                          namespace {{BaseNamespace}}.{{stateName}}.{{directionName}};

                          public partial record {{className}} : {{interfaceName}} 
                          {
                              public new ProtocolState State => ProtocolState.{{stateName}};
                              public new int Id => 0x{{id:X2}};
                          }
                          """;

        context.AddSource($"{stateName}.{directionName}/{className}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static void StartRegistry(StringBuilder sb)
    {
        sb.AppendLine($$"""
                        // <auto-generated />

                        #nullable enable

                        using System;
                        using System.Diagnostics.CodeAnalysis;

                        namespace {{BaseNamespace}};

                        public static class ServerboundPacketRegistry 
                        {
                            public static Task<IServerboundPacket?> TryDeserializePacket(
                                ProtocolState state,
                                int id,
                                NetworkStream stream,
                                BinaryReader reader,
                                CancellationToken cancellationToken)
                            {
                                return (state, id) switch
                                {
                        """);
    }

    private static void EndRegistry(StringBuilder sb)
    {
        sb.Append("""
                              _ => Task.FromResult(null)
                          };
                      
                          return packet is not null;
                      }
                  }
                  """);
    }

    private static string ToPascalCase(string input)
    {
        return string.Join("", input.Split(['_', '/'], StringSplitOptions.RemoveEmptyEntries)
            .Select(static word => char.ToUpper(word[0]) + word.Substring(1))
        );
    }

}