using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.Json;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class PacketGenerator : IIncrementalGenerator
{

    private const string BaseNamespace = "Sharpmine.Server.Protocol.Packets";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packetProvider = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("packets.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, cancellationToken) => ParsePackets(text.GetText(cancellationToken)?.ToString()))
            .SelectMany(static (packets, _) => packets)
            .Collect();

        context.RegisterSourceOutput(packetProvider, Execute);
    }

    private static ImmutableArray<PacketModel> ParsePackets(string? jsonContent)
    {
        if (string.IsNullOrWhiteSpace(jsonContent))
        {
            return ImmutableArray<PacketModel>.Empty;
        }

        using var doc = JsonDocument.Parse(jsonContent!);
        var builder = ImmutableArray.CreateBuilder<PacketModel>();

        var orderedStateProperties = doc.RootElement
            .EnumerateObject()
            .OrderBy(static prop => (prop.Value.TryGetProperty("serverbound", out var sb))
                ? sb.GetPropertyCount()
                : 0);

        foreach (var stateProperty in orderedStateProperties)
        {
            string stateName = ToPascalCase(stateProperty.Name);
            GenerateProtocolDirection(stateProperty, "Serverbound", stateName, builder);
            GenerateProtocolDirection(stateProperty, "Clientbound", stateName, builder);
        }

        return builder.ToImmutable();
    }

    private static void GenerateProtocolDirection(
        JsonProperty stateProperty,
        string directionName,
        string stateName,
        ImmutableArray<PacketModel>.Builder builder)
    {
        if (!stateProperty.Value.TryGetProperty(directionName.ToLower(), out var packetsElement))
        {
            return;
        }

        foreach (var packet in packetsElement.EnumerateObject())
        {
            int id = packet.Value.GetProperty("protocol_id").GetInt32();
            string rawName = packet.Name.StartsWith("minecraft:") ? packet.Name.Substring(10) : packet.Name;
            string packetName = ToPascalCase(rawName);
            string className = packetName + "Packet";
            builder.Add(new PacketModel(directionName, packetName, className, stateName, id));
        }
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<PacketModel> packets)
    {
        if (packets.IsDefaultOrEmpty) return;

        var crossStateKeys = new HashSet<(string, string)>(
            packets
                .GroupBy(static p => (p.Direction, p.PacketName))
                .Where(static g => g.Count() > 1)
                .Select(static g => g.Key));

        foreach (var packet in packets)
        {
            bool isCrossState = crossStateKeys.Contains((packet.Direction, packet.PacketName));
            GeneratePacketPartial(context, packet, isCrossState);
        }

        GenerateRegistry(context, [.. packets.Where(p => p.Direction == "Serverbound")]);
        GenerateCrossStateFactory(context, packets);
    }

    private static void GeneratePacketPartial(SourceProductionContext context, PacketModel packet, bool isCrossState)
    {
        string containingNamespace = $"{BaseNamespace}.{packet.StateName}.{packet.Direction}";
        string modifier = isCrossState ? "override " : "";
        string inheritance = isCrossState
            ? $"{BaseNamespace}.Abstract.{packet.Direction}.{packet.PacketName}Packet"
            : $"I{packet.Direction}Packet";

        string source = $$"""
                          // <auto-generated />

                          using System;

                          namespace {{containingNamespace}};

                          public partial record {{packet.ClassName}} : {{inheritance}} 
                          {
                              public {{modifier}}ProtocolState State => ProtocolState.{{packet.StateName}};
                              public {{modifier}}int Id => 0x{{packet.Id:X2}};
                          }
                          """;

        context.AddSource($"{containingNamespace}/{packet.ClassName}.Protocol.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static void GenerateRegistry(SourceProductionContext context, ImmutableArray<PacketModel> serverboundPackets)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
                        // <auto-generated />

                        #nullable enable

                        using System.Diagnostics.CodeAnalysis;

                        namespace {{BaseNamespace}};

                        public static class ServerboundPacketRegistry 
                        {
                            public static bool TryCreatePacket(
                                ProtocolState state,
                                int id,
                                [NotNullWhen(true)] out IServerboundPacket? packet)
                            {
                                packet = (state, id) switch
                                {
                        """);

        foreach (var packet in serverboundPackets)
        {
            sb.AppendLine($"            (ProtocolState.{packet.StateName}, 0x{packet.Id:X2}) => new {packet.StateName}.Serverbound.{packet.ClassName}(),");
        }

        sb.Append("""
                              _ => null
                          };
                      
                          return packet is not null;
                      }
                  }
                  """);

        context.AddSource($"{BaseNamespace}/ServerboundPacketRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateCrossStateFactory(SourceProductionContext context, ImmutableArray<PacketModel> packets)
    {
        var crossStateGroups = packets
            .GroupBy(static p => (p.Direction, p.PacketName))
            .Where(static g => g.Count() > 1);

        foreach (var group in crossStateGroups)
        {
            var sb = new StringBuilder();
            sb.AppendLine($$"""
                            // <auto-generated />

                            #nullable enable

                            using System;

                            namespace {{BaseNamespace}}.Abstract.{{group.Key.Direction}};

                            public abstract partial record {{group.Key.PacketName}}Packet : I{{group.Key.Direction}}Packet
                            {
                                public abstract ProtocolState State { get; }
                                public abstract int Id { get; }
                            """);

            if (group.Key.Direction == "Clientbound")
            {
                sb.AppendLine($$"""

                                    public static {{group.Key.PacketName}}Packet? Create(ProtocolState state)
                                    {
                                        return state switch
                                        {
                                """);

                foreach (var packet in group)
                {
                    sb.AppendLine($"            ProtocolState.{packet.StateName} => new {BaseNamespace}.{packet.StateName}.{packet.Direction}.{packet.ClassName}(),");
                }

                sb.AppendLine("""
                                          _ => null
                                      };
                                  }
                              """);
            }

            sb.Append('}');
            context.AddSource($"{BaseNamespace}.Abstract.{group.Key.Direction}/{group.Key.PacketName}Packet.Abstract.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static string ToPascalCase(string input)
    {
        return string.Join(
            string.Empty,
            input.Split(['_', '/'], StringSplitOptions.RemoveEmptyEntries)
                .Select(static word => char.ToUpper(word[0]) + word.Substring(1)));
    }

    private readonly record struct PacketModel(
        string Direction,
        string PacketName,
        string ClassName,
        string StateName,
        int Id);

}
