using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.Win32.SafeHandles;

namespace Sharpmine.Gen;

[Generator]
public class PacketPropertyGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fieldDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sharpmine.Server.Protocol.Attributes.PacketPropertyAttribute",
                predicate: static (node, _) => node is VariableDeclaratorSyntax,
                transform: static (ctx, _) => GetFieldInfo(ctx))
            .Where(static info => info is not null);

        var classGroups = fieldDeclarations.Collect()
            .SelectMany(static (fields, _) => fields.GroupBy(f => f!.Value.ClassName));

        context.RegisterSourceOutput(classGroups, Execute);
    }

    private static FieldInfo? GetFieldInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not IFieldSymbol fieldSymbol) return null;

        var classSymbol = fieldSymbol.ContainingType;
        if (classSymbol is null) return null;

        string fieldName = fieldSymbol.Name;

        string propertyName = (fieldName.StartsWith("_"))
            ? (char.ToUpper(fieldName[1]) + fieldName.Substring(2))
            : (char.ToUpper(fieldName[0]) + fieldName.Substring(1));

        string typeKeyword = (classSymbol.IsRecord, classSymbol.IsValueType) switch
        {
            (true, true) => "record struct",
            (true, false) => "record",
            (false, true) => "struct",
            (false, false) => "class",
        };

        return new FieldInfo(
            Namespace: classSymbol.ContainingNamespace.ToDisplayString(),
            TypeKeyword: typeKeyword,
            ClassName: classSymbol.Name,
            FieldType: fieldSymbol.Type.ToDisplayString(),
            FieldName: fieldName,
            PropertyName: propertyName
        );
    }

    private static void Execute(SourceProductionContext context, IGrouping<string, FieldInfo?> group)
    {
        var fields = group.ToList();
        if (fields.Count == 0) return;

        var first = fields[0]!.Value;
        var sb = new StringBuilder();

        sb.AppendLine($$"""
                        // <auto-generated />

                        #nullable enable

                        namespace {{first.Namespace}};

                        public partial {{first.TypeKeyword}} {{first.ClassName}}
                        {
                        """);

        sb.AppendLine();
        sb.AppendLine($"    public {first.ClassName}()");
        sb.AppendLine("    {");

        foreach (var info in fields.Select(field => field!.Value))
        {
            sb.AppendLine($"        {info.FieldName} = default!;");
        }

        sb.AppendLine("    }");

        foreach (var info in fields.Select(field => field!.Value))
        {
            sb.AppendLine($"    public {info.FieldType} {info.PropertyName} => {info.FieldName};");
        }

        sb.AppendLine("}");

        context.AddSource($"{first.Namespace}/{first.ClassName}.Properties.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly record struct FieldInfo(
        string Namespace,
        string TypeKeyword,
        string ClassName,
        string FieldType,
        string FieldName,
        string PropertyName);

}
