using System.Linq;
using System.Text;
using System.Text.Json;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class StaticRegistryGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registryContents = context.AdditionalTextsProvider
            .Where(static file => file.Path.Replace('\\', '/').EndsWith("/reports/registries.json"))
            .Select(static (text, ct) => text.GetText(ct)?.ToString())
            .Collect();

        context.RegisterSourceOutput(registryContents, (spc, allContents) =>
        {
            if (allContents.IsDefaultOrEmpty) return;

            string? content = allContents.FirstOrDefault(c => !string.IsNullOrWhiteSpace(c));
            if (string.IsNullOrWhiteSpace(content)) return;

            try
            {
                using var document = JsonDocument.Parse(content!);
                var root = document.RootElement;

                foreach (var registry in root.EnumerateObject())
                {
                    string registryName = registry.Name.Replace("minecraft:", string.Empty);

                    if (registryName is "block" or "item") continue;

                    string className = FormatClassName(registryName); // e.g., "entity_type" -> "EntityTypes"
                    var entriesNode = registry.Value.GetProperty("entries");

                    var sb = new StringBuilder($$"""
                                                 // <auto-generated/>

                                                 using Sharpmine.Domain;

                                                 namespace Sharpmine.Domain.Registries.Static;

                                                 public static class {{className}}
                                                 {

                                                 """);

                    foreach (string fullId in entriesNode.EnumerateObject().Select(entry => entry.Name))
                    {
                        string propertyName = GeneratorUtils.ToPascalCase(fullId.Replace("minecraft:", string.Empty));
                        sb.AppendLine($"    public static readonly Identifier {propertyName} = \"{fullId}\";");
                    }

                    sb.AppendLine("}");
                    spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
                }
            }
            catch
            {
                // Fail silently
            }
        });
    }

    private static string FormatClassName(string input)
    {
        string pascal = GeneratorUtils.ToPascalCase(input);
        if (pascal.EndsWith("y")) return pascal.Substring(0, pascal.Length - 1) + "ies";
        if (pascal.EndsWith("s")) return pascal;
        return pascal + 's';
    }

}
