using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class TagGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var tagFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.Replace('\\', '/').Contains("/minecraft/tags/") && file.Path.EndsWith(".json"))
            .Collect();

        context.RegisterSourceOutput(tagFiles, (spc, files) =>
        {
            if (files.IsDefaultOrEmpty) return;

            var tagsByRegistryType = new Dictionary<string, List<(string PropertyName, string FullId)>>();

            foreach (var file in files)
            {
                // .../data/minecraft/tags/block/mineable/pickaxe.json
                string[] parts = file.Path.Split('/', '\\');
                int tagsIndex = System.Array.IndexOf(parts, "tags");

                if (tagsIndex == -1 || parts.Length <= tagsIndex + 2)
                {
                    continue;
                }

                string registryType = parts[tagsIndex + 1]; // "block", "item"

                if (!tagsByRegistryType.TryGetValue(registryType, out var value))
                {
                    value = [];
                    tagsByRegistryType[registryType] = value;
                }

                // "mineable/pickaxe"
                string tagPath = string.Join("/", parts.Skip(tagsIndex + 2)).Replace(".json", string.Empty);
                value.Add((GeneratorUtils.ToPascalCase(tagPath), "minecraft:" + tagPath));
            }

            foreach (var group in tagsByRegistryType)
            {
                string className = GeneratorUtils.ToPascalCase(group.Key) + "Tags";

                var sb = new StringBuilder($$"""
                                             // <auto-generated/>

                                             using Sharpmine.Domain;

                                             namespace Sharpmine.Domain.Tags;

                                             public static class {{className}}
                                             {

                                             """);
                foreach (var tag in group.Value)
                {
                    sb.AppendLine($"    public static readonly Identifier {tag.PropertyName} = \"{tag.FullId}\";");
                }

                sb.AppendLine("}");
                spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        });
    }

}
