using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sharpmine.Gen;

[Generator]
public class TagGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var tagFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.Replace('\\', '/').Contains("/minecraft/tags/") && file.Path.EndsWith(".json"))
            .Collect();

        context.RegisterSourceOutput(tagFiles, (spc, files) =>
        {
            if (files.IsDefaultOrEmpty) return;

            var rawTags = new Dictionary<string, List<string>>();
            var tagsByRegistryType = new Dictionary<string, List<(string PropertyName, string FullId)>>();

            foreach (var file in files)
            {
                // .../data/minecraft/tags/block/mineable/pickaxe.json
                string[] parts = file.Path.Split('/', '\\');
                int tagsIndex = System.Array.IndexOf(parts, "tags");

                if (tagsIndex == -1 || parts.Length <= tagsIndex + 2)
                {
                    continue;
                }

                string registryType = parts[tagsIndex + 1]; // "block", "item", "worldgen"
                int tagIdStartIndex = tagsIndex + 2;

                if (registryType == "worldgen" && parts.Length > tagsIndex + 3)
                {
                    registryType += '/' + parts[tagIdStartIndex++]; // "worldgen/biome"
                }

                // "mineable/pickaxe"
                string tagPath = string.Join("/", parts.Skip(tagIdStartIndex)).Replace(".json", string.Empty);
                string tagFullId = "#minecraft:" + tagPath;

                string? jsonText = file.GetText()?.ToString();
                if (string.IsNullOrWhiteSpace(jsonText)) continue;

                var values = ExtractValuesFromJson(jsonText!);
                rawTags[tagFullId] = values;

                if (!tagsByRegistryType.TryGetValue(registryType, out var valueList))
                {
                    valueList = [];
                    tagsByRegistryType[registryType] = valueList;
                }

                valueList.Add((GeneratorUtils.ToPascalCase(tagPath), tagFullId));
            }

            foreach (var group in tagsByRegistryType)
            {
                string className = GeneratorUtils.ToPascalCase(group.Key) + "Tags";

                var sb = new StringBuilder($$"""
                                             // <auto-generated/>
                                             using System.Collections.Concurrent;
                                             using System.Collections.Frozen;
                                             using Sharpmine.Domain;

                                             namespace Sharpmine.Domain.Tags;

                                             public static class {{className}}
                                             {

                                             """);
                foreach (var tag in group.Value)
                {
                    var flattenedValues = ResolveTagValues(tag.FullId, rawTags, []);
                    string arrayElements = string.Join(", ", flattenedValues.Select(v => $"\"{v}\""));
                    sb.AppendLine($"    public static readonly RegistryTagDto {tag.PropertyName} = new(\"{tag.FullId}\", [{arrayElements}]);");
                }

                if (group.Key == "block")
                {
                    sb.AppendLine("""

                        private static readonly ConcurrentDictionary<Identifier, FrozenSet<int>> _stateCache = [];

                        public static FrozenSet<int> GetStates(RegistryTagDto tag)
                        {
                            return _stateCache.GetOrAdd(tag.Id, _ => tag.Values
                                .Select(id => Registries.Static.Blocks.All[id])
                                .SelectMany(block => block.States)
                                .Select(state => state.Id)
                                .ToFrozenSet());
                        }
                    """);
                }

                sb.AppendLine("}");
                spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        });
    }

    private static HashSet<string> ResolveTagValues(string tagId, Dictionary<string, List<string>> allTags, HashSet<string> visited)
    {
        var result = new HashSet<string>();

        // Prevent infinite recursion in the case of circular tag references
        if (!visited.Add(tagId) || !allTags.TryGetValue(tagId, out var rawValues))
        {
            return result;
        }

        foreach (string value in rawValues)
        {
            if (value.StartsWith("#"))
            {
                result.UnionWith(ResolveTagValues(value, allTags, visited));
            }
            else
            {
                result.Add(value);
            }
        }

        return result;
    }

    private static List<string> ExtractValuesFromJson(string jsonText)
    {
        var list = new List<string>();

        try
        {
            using var doc = JsonDocument.Parse(jsonText);

            if (doc.RootElement.TryGetProperty("values", out var valuesNode) && valuesNode.ValueKind == JsonValueKind.Array)
            {
                foreach (var item in valuesNode.EnumerateArray())
                {
                    // "minecraft:dirt" / "#minecraft:rails"
                    if (item.ValueKind == JsonValueKind.String)
                    {
                        list.Add(item.GetString()!);
                    }
                    // { "id": "#minecraft:rails", "required": false }
                    else if (item.ValueKind == JsonValueKind.Object && item.TryGetProperty("id", out var idProp))
                    {
                        list.Add(idProp.GetString()!);
                    }
                }
            }
        }
        catch
        {
            // Ignore
        }

        return list;
    }

}
